### ISSUE TITLE
Action pinned at SHA does not work.

### ISSUE THREAD

**Issue by FiV0** [bubkoo/auto-close-issues#4]
### Expected Behavior

Action should work when pinned to SHA hash.

### Current Behavior

Action fails with 
```
Error: File not found: '/home/runner/work/_actions/wow-actions/auto-close-fixed-issues/000037415349b8d6a8d2eb8304cba497d5d55647/dist/index.js'
```

Also see https://github.com/xtdb/xtdb/actions/runs/4872013283/jobs/8689683120

### Possible Solution

Not considered.

### Steps To Reproduce

This is what our current action looks like:
```yaml
name: Auto Close Issues

on:
  pull_request:
    types: [closed]

jobs:
  close:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: wow-actions/auto-close-fixed-issues@000037415349b8d6a8d2eb8304cba497d5d55647
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # optional comment
          # comment: 'This issue was closed by #{{ pr }}.'
          # default ignore the pr merge to the default branch
          # ignore: true
```

<details><summary>Error Message & Stack Trace</summary><p>

See above. 

### Your Environment

Github Actions
